/**
 * Static class consisting of functions for parsing a Pronto Hex string (like 0000 006C 0022 0002 015B 00AD ...)  into an IrSignal,
 * and vice versa.
 * <a href="http://harctoolbox.org/Glossary.html#ProntoSemantics">Reference</a>.
 *
 * Note: Unless you have "infinitely much" memory, it is a very bad idea to put Pronto Hex in your source files.
 * Better is to use, for example IrScruitinizer to convert the signals offline,
 * and put the converted version in your source files instead.
 *
 * This class presently does not use floating point arithmetics.
 */

#pragma once

#include "InfraredTypes.h"
#include "IrSignal.h"
#include "Board.h"

class Pronto {
private:
    typedef uint16_t prontoInt;

    static const prontoInt learnedToken = 0x0000;
    static const prontoInt learnedNonModulatedToken = 0x0100;
    static const unsigned int bitsInHexadecimal = 4;
    static const unsigned int digitsInProntoNumber = 4;
    static const unsigned int numbersInPreamble = 4;
    static const unsigned int hexMask = 0xF;
    static const unsigned int charsInPreamble = numbersInPreamble * (digitsInProntoNumber + 1);
    static const uint32_t referenceFrequency = 4145146UL;
    static const prontoInt fallbackFrequencyCode = 0x0040; // To use with frequency = 0;
    static const frequency_t fallbackFrequency = 64767U; // To use with frequency = 0;
    static const uint32_t microsecondsInSeconds = 1000000UL;

    Pronto() {};

    static IrSequence *mkSequence(const uint16_t *data, size_t pairs, microseconds_t timebase);

    static frequency_t toFrequency(prontoInt code);

    static prontoInt toFrequencyCode(frequency_t frequency);

    static frequency_t effectiveFrequency(frequency_t frequency);

    static microseconds_t toTimebase(frequency_t frequency_t);

    static size_t lengthHexString(size_t introLength, size_t repeatLength);

    static char* setup(frequency_t frequency, size_t introLength, size_t repeatLength);

    static char hexDigit(unsigned int x);

    static unsigned int appendChar(char *result, unsigned int index, char ch);

    static unsigned int appendDuration(char *result, unsigned int index, prontoInt duration, microseconds_t timebase);

    static unsigned int appendDigit(char *result, unsigned int index, unsigned int number);

    static unsigned int appendNumber(char *result, unsigned int index, prontoInt number);

    static unsigned int appendSequence(char *result, unsigned int index, const microseconds_t *data, size_t length, microseconds_t timebase);

    static unsigned int appendSequence(char *result, unsigned int index, const IrSequence& irSequence, microseconds_t timebase);

public:
    /**
     * Function for parsing its input data into an IrSignal. The ending sequence will always be empty.
     * @param data Numerical data, the number in the Pronto form.
     * @param size Number of data points.
     * @return IrSignal
     */
    static IrSignal *parse(const uint16_t *data, size_t size);

    /**
     * Function for parsing its input data into an IrSignal. The ending sequence will always be empty.
     * @param str Text string containing a Pronto form signal.
     * @return IrSignal
     */
    static IrSignal *parse(const char *str);

    /**
     * Function for parsing its input data into an IrSignal. The ending sequence will always be empty.
     * @param str Text string containing a Pronto form signal.
     * @return IrSignal
     */
    static IrSignal *parse_PF(const uint_farptr_t ptr);

    static IrSignal *parse_PF(const char * ptr);

//#if defined(ARDUINO) || defined(DOXYGEN)
    /**
     * Function for parsing its input data into an IrSignal. The ending sequence will always be empty.
     * @param str Text string containing a Pronto form signal.
     * This form handles the F(...) form.
     * Available only on platforms implementing the str*_PF functions.
     * @return IrSignal
     */
    static IrSignal *parse(const __FlashStringHelper *str);
//#endif

    /**
     * Function for generating a Pronto Hex string from the argument.
     * @param irSignal
     * @return Zero terminated string. Has been generated by new[], and must be manually delete[]-d by the user.
     */
    static char* toProntoHex(const IrSignal& irSignal);

    /**
     * Function for generating a Pronto Hex string from the argument.
     * @param data
     * @param length
     * @param frequency
     * @return Zero terminated string. Has been generated by new[], and must be manually delete[]-d by the user.
     */
    static char* toProntoHex(const microseconds_t* data, size_t length, frequency_t frequency = IrSignal::defaultFrequency);

    /**
     * Function for generating a Pronto Hex string from the argument.
     * @param irSequence
     * @param frequency
     * @return Zero terminated string. Has been generated by new[], and must be manually delete[]-d by the user.
     */
    static char* toProntoHex(const IrSequence& irSequence, frequency_t frequency = IrSignal::defaultFrequency);
};
